### ISSUE TITLE
Front-end work to accomodate subtasks

### ISSUE THREAD

**Issue by lilyosah** [lilyosah/COSC415-ToDo#133]
- [ ] Decide for sections like upcoming and overdue (`_tasks_single_section` partial) we want all subtasks and due dates to be listed separately like in the two section or want them all combined into one list ordered by date (will eventually add other sorting when we add groups). We could also add the option to switch between the two views! I like that more. So a button to switch between the due and work sections and listing all of the tasks in one list ordered by date.
   - [ ] For one list: Make sure subtasks/to work on are represented by circle checkmarks. 
   - [ ] For things that are due, make sure they use the square checkmarks but also maybe add "due" after the task name to further make it clear that these were due dates.
